# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-08-17T12:48:58Z"
  labels:
    app: my-pod
  name: my-pod
spec:
  containers:
  - command:
    - mongod
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: my-pod
    - name: container
      value: podman
    - name: MONGO_PACKAGE
      value: mongodb-org
    - name: MONGO_REPO
      value: repo.mongodb.org
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "1234"
    - name: GPG_KEYS
      value: 20691EEC35216C63CAF66CE1656408E390CFB1F5
    - name: JSYAML_VERSION
      value: 3.13.1
    - name: MONGO_MAJOR
      value: "4.4"
    - name: MONGO_VERSION
      value: 4.4.0
    - name: GOSU_VERSION
      value: "1.12"
    image: docker.io/library/mongo:latest
    name: mongodb
    ports:
    - containerPort: 3000
      hostPort: 8080
      protocol: TCP
    - containerPort: 27017
      hostPort: 27017
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /
  - command:
    - /wait-for-it.sh
    - db:27017
    - --
    - npm
    - run
    - start:dev
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: my-pod
    - name: container
      value: podman
    - name: NODE_VERSION
      value: 12.18.3
    - name: YARN_VERSION
      value: 1.22.4
    image: docker.io/shockz/nodetest:0.4
    name: nodetest
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /usr/src/nodetest
      name: home-shockz-nodetest
    workingDir: /usr/src/nodetest
  volumes:
  - hostPath:
      path: /home/shockz/nodetest
      type: Directory
    name: home-shockz-nodetest
status: {}

